---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
- name: ci-images-git-repo
outputs:
- name: image
caches:
- path: ci-image-cache
params:
  CONTEXT: ci-images-git-repo/ci/images
  DOCKERFILE: ci-images-git-repo/ci/images/((ci-image-name))/Dockerfile
  REGISTRY_MIRRORS: ((dockerhub-registry-mirror))
run:
  path: build
